### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by aleeusgr** [SIDANWhatever/plutus-cborhex-automation#1]
~~[Miro](https://miro.com/app/board/uXjVOmOBZ14=/)~~
~~TODO: Design Speck from James~~

Thank you!

**Comment by aleeusgr** [comment]
~~[this](https://github.com/Hyperion-BT/Helios)~~
~~?~~

Later

**Comment by HinsonSIDAN** [comment]
We have several documentation to draft up:
1. `Readme.md` for this repo: A brief draft is done, we could iterate and update it alone the way.
2. Example script: A documentation for example scripts and how to use it.
3. Docker: A documentation for how to get haskell functions up and running in docker.
4. Final module: This is the most important one - the documentation on how to use our module.

For other resources such as `Helios` we could just look around along the way, to see if it is useful and change our direction. But what we have aligned today is what we are going to look around first - if there is no significant blocker we could just go as discussed, to implement Haskell backend with docker micro-service deployment.

**Comment by aleeusgr** [comment]
added 2 as an [issue](https://github.com/SIDANWhatever/plutus-cborhex-automation/issues/5)
[working on 3](https://github.com/SIDANWhatever/plutus-cborhex-automation/issues/2)

**Comment by aleeusgr** [comment]
How to specify Validator Parameters related to that Contract

**Comment by aleeusgr** [comment]
How to use local endpoint that takes Parameters and returns CBOR + Address

**Comment by aleeusgr** [comment]
> added 2 as an [issue](https://github.com/SIDANWhatever/plutus-cborhex-automation/issues/5)
> [working on 3](https://github.com/SIDANWhatever/plutus-cborhex-automation/issues/2)

https://gitlab.com/gimbalabs/plutus-pbl-summer-2022/plutus-always-succeeds

**Comment by aleeusgr** [comment]
3: https://github.com/aleeusgr/hello-haskell-ci/commit/0a62b34b070cb5a3210319e613d194d17b73d887

**Comment by HinsonSIDAN** [comment]
Closing as completed
