### ISSUE TITLE
Plutus Research: Common parameter data type

### ISSUE THREAD

**Issue by HinsonSIDAN** [SIDANWhatever/plutus-cborhex-automation#23]
This is for gather a list of common parameter data type for implementation of [issue 4](https://github.com/SIDANWhatever/plutus-cborhex-automation/issues/4). A few examples are below:

```haskell
Integer
String
CurrencySymbol
TokenName
AssetClass
POSIXTime
PaymentPubKeyHash
PubKeyHash
```

@aleeusgr Please help to explore current contracts implemented by Gimbalabs to check if there is any missing from above

**Comment by aleeusgr** [comment]
## Motivation
In the next release, we aim to supply users with a set of prepared smart contracts. 
So we have to decide: 
1. How many contracts to supply? 
2. What contracts do we supply?
3. Exactly what parameters can be changed for each contract?

A challenge to consider is that web-API does not provide specific data types that Plutus scripts are using, therefore we have to convert them. Not all parameters are created equally: for some, their data type can be easily inferred, and probably there are parameters that are impossible to use in this way.

Therefore our decision has to be balanced between 
"how useful a given parameterized smart contract will be to the end user?" 
and 
"how difficult it is to implement?"

**Comment by aleeusgr** [comment]
I think ultimately we should aim to support Gimbalabs Project Treasury, which has two smart contracts - Treasury and Bounty.

An alternative could be a smart contract that has potential for being used often, and has a set of parameters that are easy to work with.

**Comment by aleeusgr** [comment]
## faucet

```
SENDER=
SENDERKEY=
CONTRACT_TXIN=
AUTH_TOKEN_TXIN=
FEE_TXIN=
COLLATERAL=
```

```
PLUTUS_SCRIPT_FILE="<YOUR PATH TO>/ppbl-course-02/project-301-faucet/output/ppbl-faucet-preprod-2022-oct-tgimbal.plutus"
ASSET="fb45417ab92a155da3b31a8928c873eb9fd36c62184c736f189d334c.7447696d62616c"
AUTH_TOKEN="748ee66265a1853c6f068f86622e36b0dda8edfa69c689a7dd232c60.5050424c32303232416363657373546f6b656e"
TOKENS_BACK_TO_CONTRACT=<NUMBER tGimbals IN CONTRACT> - 1000
CONTRACTADDR=addr_test1wqunsl063ezhn67r72uxetvjugrmnnrkqu8pmd9exc6lcdcgnt2uf
DATUMHASH=2da1c63e7646ce8cc514113c66e9cefb79e482210ad1dadb51c2a17ab14cf114
```

**Comment by aleeusgr** [comment]
data FaucetParams = FaucetParams
  { ~~accessTokenSymbol   :: !CurrencySymbol~~
  , ~~accessTokenName     :: !TokenName~~
  , ~~faucetTokenSymbol   :: !CurrencySymbol~~
  , ~~faucetTokenName     :: !TokenName~~
  , ~~withdrawalAmount`    :: !Integer~~
  } deriving (Pr.Eq, Pr.Ord, Show, Generic, ToJSON, FromJSON, ToSchema)

**Comment by HinsonSIDAN** [comment]
How many contracts to supply?
--> Now user can supply their own plutus script for the service (but limited to one parameter only)

What contracts do we supply?
--> Their own, for both minting policy & validator (with both V1 V2 supported)

Exactly what parameters can be changed for each contract?
--> Any custom parameter, but limited to one only at the moment

**Comment by HinsonSIDAN** [comment]
A quick design choice has been made, where parameter data type is handled in JSON body crafting process. So this issue turns out to be about documentation guide on know-how instead of implementing on Haskell lib

**Comment by HinsonSIDAN** [comment]
Closing it for now as we have covered most param types in docs.
