### ISSUE TITLE
Choosing featured contracts.

### ISSUE THREAD

**Issue by aleeusgr** [SIDANWhatever/plutus-cborhex-automation#25]
## From James:

1. Token Gated Faucet from PPBL - I think of this almost like a hello world (it's a bit more than Always Succeeds, but still very simple, and shows an essential thing that Plutus can do): https://gitlab.com/gimbalabs/plutus-pbl-summer-2022/ppbl-course-02/-/tree/master/project-301-faucet

2. Treasury and Escrow contracts as in GPTE: https://gitlab.com/gimbalabs/plutus-pbl-summer-2022/projects/gpte/gpte-plutus-v2

3. Yes, I think a DAO-facing micro-DEX instance is a good idea. Would be fun to build this.

4. Rails for CIP-68 style metadatum token pairs - which includes a simple gatekeeping contract for updating the datum: https://gitlab.com/gimbalabs/plutus-pbl-summer-2022/projects/completion-token/ppbl-contributor-token

5. Similar to (3), instances of NFT marketplaces - Martify team is working on this from a front end perspective

**Comment by HinsonSIDAN** [comment]
New branch `featrure/gimbalabs-integration` has been created for this purpose. You can try to integrate them in our latest beta release @aleeusgr

**Comment by HinsonSIDAN** [comment]
closing as completed
