### ISSUE TITLE
Decomposing token-gated Faucet

### ISSUE THREAD

**Issue by aleeusgr** [SIDANWhatever/plutus-cborhex-automation#26]
@SIDANWhatever  — Yesterday at 17:56
>Okay, then maybe you try to understand the above 3 contracts first and give me some time to develop the package function

https://gitlab.com/gimbalabs/plutus-pbl-summer-2022/ppbl-course-02/-/tree/master/project-301-faucet

**Comment by aleeusgr** [comment]
## Extensions and imports.
Lines 1: 12 are [extensions](https://kowainik.github.io/posts/extensions)
15: 18 - FaucetValidatorScript has 2 parameters: FaucetParam and Validator..??
21:31 - [Imports](https://wiki.haskell.org/Import).

`import Data.Aeson (ToJSON, FromJSON)` means only 2 functions are imported

[qualified imports](https://stackoverflow.com/questions/11274864/what-does-qualified-mean-in-import-qualified-data-list-statement)

**Comment by aleeusgr** [comment]
## THe parameters

```haskell
data FaucetParams = FaucetParams
  { accessTokenSymbol   :: !CurrencySymbol
  , accessTokenName     :: !TokenName
  , faucetTokenSymbol   :: !CurrencySymbol
  , faucetTokenName     :: !TokenName
  , withdrawalAmount    :: !Integer
  } deriving (Pr.Eq, Pr.Ord, Show, Generic, ToJSON, FromJSON, ToSchema)
```
[deriving](https://stackoverflow.com/questions/3864647/how-does-deriving-work-in-haskell)

**Comment by aleeusgr** [comment]
[makeLift](https://playground.plutus.iohkdev.io/doc/haddock/plutus-tx/html/PlutusTx-Lift-Class.html#v:makeLift)
unstableMakeIsData - ??
```
55. PlutusTx.makeLift ''FaucetParams

...

59. PlutusTx.unstableMakeIsData ''FaucetRedeemer
60. PlutusTx.makeLift ''FaucetRedeemer

```

**Comment by aleeusgr** [comment]
`newtype FaucetRedeemer` - ??
[PubKeyHash](https://playground.plutus.iohkdev.io/doc/haddock/plutus-ledger/html/Ledger.html#t:PubKeyHash)


```haskell
newtype FaucetRedeemer = FaucetRedeemer {senderPkh :: PubKeyHash}
```
```  
faucetValidator :: FaucetParams -> Integer -> FaucetRedeemer -> ScriptContext -> Bool
faucetValidator faucet _ receiver ctx =  traceIfFalse "Input needs PPBL2022AccessToken"           inputHasAccessToken &&
                                                  traceIfFalse "PPBL2022AccessToken must return to sender" outputHasAccessToken &&
                                                  traceIfFalse "Faucet token must be distributed to sender" outputHasFaucetToken &&
                                                  traceIfFalse "Must return remaining tokens to contract"   faucetContractGetsRemainingTokens &&
                                                  traceIfFalse "Do we need to check datum"                  checkDatumIsOk
```

[Compare](https://github.com/SIDANWhatever/plutus-cborhex-automation/blob/89ea6b7808849f92113b551a9bed9d7bd5763943/example/src/TestingValidator.hs#L60) 
```
mkValidator :: TestParam -> Integer -> () -> Plutus.ScriptContext -> Bool
mkValidator param dat _ _ = dat == testNumber param```

**Comment by HinsonSIDAN** [comment]
`makeLift` - low level haskell function for deriving instances in order to make data usable in plutus-core
`unstableMakeIsData` - deriving instances for haskell function to understand JSON format for this data type in a particular order
`newtype` - same as data declaration, just for this data type, there is only one value constructor with one element stored inside. This is introduced for efficiency purposes

-- upon basic research, you can try to implement the 3 contracts into endpoints as described at #25

**Comment by aleeusgr** [comment]
`SIDAN.createEndpoint "get-parameterized-script" $ SIDAN.mkV1Validator V1V.validator`

**Comment by aleeusgr** [comment]
`withdrawalAmount`

https://github.com/aleeusgr/plutus-cborhex-automation/blob/d95ad01fc9b00bc0f575b37d3d713dc02770e6d1/example/src/FaucetValidatorScript.hs#L52

https://github.com/aleeusgr/plutus-cborhex-automation/blob/d95ad01fc9b00bc0f575b37d3d713dc02770e6d1/example/src/FaucetValidatorScript.hs#L89

https://github.com/aleeusgr/plutus-cborhex-automation/blob/d95ad01fc9b00bc0f575b37d3d713dc02770e6d1/example/src/FaucetValidatorScript.hs#L110

**Comment by aleeusgr** [comment]
So how does that work?

If Validator confirms the details of a transaction, it [signals the on-chain part to execute it].

This is a gated faucet, it generates tokens out of thin air.
It could be used in a economic loop where tokens are constantly created and burned,
E.g.: On-Chain Governance of Decentralized Autonomous Organizations: Blockchain Organization Using Semada, Calcaterra C.

To get your free tokens, you need a transaction (link to (how to create a transaction), and an [Auth Token].

**Comment by HinsonSIDAN** [comment]
We could take this discussion offline. The use case should be covered in PPBL or other Gimbalabs resources. Closing as the integration with examples are completed
