### ISSUE TITLE
REST endpoint: research options

### ISSUE THREAD

**Issue by aleeusgr** [SIDANWhatever/plutus-cborhex-automation#3]
that returns CBOR and Address for any pre-defined, parameterized Plutus Validator.

**Comment by HinsonSIDAN** [comment]
Different Haskell libraries to tested out:
https://hackage.haskell.org/package/servant-server
https://www.yesodweb.com/
https://hackage.haskell.org/package/scotty-0.12/docs/Web-Scotty.html

**Comment by aleeusgr** [comment]
there is a [doc on Yesod + docker](https://thoughtbot.com/blog/easy-haskell-development-and-deployment-with-docker)

**Comment by aleeusgr** [comment]
Haskell: state of the ecosystem 

https://github.com/Gabriella439/post-rfc/blob/main/sotu.md

**Comment by aleeusgr** [comment]
I could not make this work
> there is a [doc on Yesod + docker](https://thoughtbot.com/blog/easy-haskell-development-and-deployment-with-docker)

testing `docker build`

[Yesod web Server from scratch](https://www.yesodweb.com/page/quickstart)

❌ I get [various errors](https://github.com/SIDANWhatever/plutus-cborhex-automation/issues/16)

**Comment by aleeusgr** [comment]
https://github.com/phadej/docker-haskell-example

>Hello @phadej! I was looking for some multi-stage build Dockerfiles for Haskell projects and I happened upon this one, which has some great tips. I think one currently agreed-upon Docker best practice is missing, though, from your Dockerfile: don't run processes as root. It may be worth changing here if people are finding your blog-post and copying the code in there? I could probably submit a PR to this repo if you think it's worth it.

09:00 $ `cabal run`
cabal: Could not resolve dependencies:                                                                                 
[__0] trying: docker-haskell-example-0 (user goal)                                                                     
[__1] trying: warp-3.2.27 (dependency of docker-haskell-example)                                                       
[__2] trying: wai-3.2.2 (dependency of warp)                                                                           
[__3] trying: transformers-0.5.6.2/installed-0.5.6.2 (dependency of wai)                                               
[__4] next goal: vault (dependency of warp)                                                                            
[__4] rejecting: vault-0.3.1.2 (conflict: transformers =>base==4.15.1.0/installed-4.15.1.0, vault => base>=4.5 && <4.13)

**Comment by aleeusgr** [comment]
zlib                         > Configuring zlib-0.6.3.0...                                                             cryptonite                   > [109 of 137] Compiling Crypto.KDF.BCrypt                                                
zlib                         > Cabal-simple_mPHDZzAJ_3.4.1.0_ghc-9.0.2: Missing dependency on a foreign                
zlib                         > library:                                                                                
zlib                         > * Missing (or bad) header file: zlib.h                                                  
zlib                         > * Missing (or bad) C library: z                                                         
zlib                         > This problem can usually be solved by installing the system package that                
zlib                         > provides this library (you may need the "-dev" version). If the library is              
zlib                         > already installed but in a non-standard location then you can use the flags             
zlib                         > --extra-include-dirs= and --extra-lib-dirs= to specify where it is.If the               
zlib                         > library file does exist, it may contain errors that are caught by the C                 
zlib                         > compiler at the preprocessing stage. In this case you can re-run configure              
zlib                         > with the verbosity flag -v3 to see the error messages.                                  
zlib                         > If the header file does exist, it may contain errors that are caught by the C           
zlib                         > compiler at the preprocessing stage. In this case you can re-run configure              
zlib                         > with the verbosity flag -v3 to see the error messages.                                  
zlib                         >

**Comment by aleeusgr** [comment]
@SIDANWhatever I moved your code from `example-validator` to the root of directory. Check [this branch](https://github.com/SIDANWhatever/plutus-cborhex-automation/tree/ev-to-root), 
I get "spock running on 8080" on `nix-shell $ cabal run`  but I dunno how to query its endpoint.

plutus-apps in docker is a thing that I don't understand how to do. Adding `stack` may help, it has nix support and docker support. 

Awesome job on building Spock, respect man!!! 
I tried several implementations but keep running into same error which I've no idea what it means. It keeps me bugged

**Comment by aleeusgr** [comment]
## A generic Haskell web API in a docker image:
servant code [from here](https://docs.servant.dev/en/stable/tutorial/Server.html#a-first-example)
docker procedure [form here](https://github.com/phadej/docker-haskell-example)

**Comment by aleeusgr** [comment]
Hm, I am having difficulties not only with spock, but [other frameworks as well](https://gitlab.haskell.org/ghc/ghc/-/issues/22301). It seem I am missing something on how Haskell build system works.
Diggin

**Comment by aleeusgr** [comment]
### ✅ This builds on my machine
1. $stack new my-name [spock-template](https://github.com/commercialhaskell/stack-templates/blob/master/spock.hsfiles)
2. Maybe fix zlib, [see above](https://github.com/SIDANWhatever/plutus-cborhex-automation/issues/3#issuecomment-1278544029).
3. stack build
4. stack exec name
>Spock is running on port 8080

### Does not have `plutus-apps`, https://github.com/SIDANWhatever/plutus-cborhex-automation/issues/18 needed
