### ISSUE TITLE
`cabal run` inside example-validator returns an error.

### ISSUE THREAD

**Issue by aleeusgr** [SIDANWhatever/plutus-cborhex-automation#30]
To reproduce:

cd plutus-apps -> nix-shell -> cd example-validator -> cabal update -> cabal run

>[1 of 1] Compiling Main             ( /home/alex/workshop/plutus-cborhex-automation/example-validator/dist-newstyle/tmp/src-68418/postgresql-libpq-0.9.4.3/dist/setup/setup.hs, /home/alex/workshop/plutus-cborhex-automation/example-validator/dist-newstyle/tmp/src-68418/postgresql-libpq-0.9.4.3/dist/setup/Main.o )
Linking /home/alex/workshop/plutus-cborhex-automation/example-validator/dist-newstyle/tmp/src-68418/postgresql-libpq-0.9.4.3/dist/setup/setup ...
Configuring postgresql-libpq-0.9.4.3...
setup: The program 'pg_config' is required but it could not be found.

>cabal: Failed to build postgresql-libpq-0.9.4.3 (which is required by
exe:example-validator from example-validator-0.1.0.0). See the build log above
for details.

**Comment by aleeusgr** [comment]
Worng tag?  I used v1.0.0-alpha
```
git pull
git checkout 97b4c1da03faf9bc35f348802fb7927231657e75
nix-shell
```

**Comment by aleeusgr** [comment]
Testing.

**Comment by HinsonSIDAN** [comment]
> Worng tag?  I used v1.0.0-alpha
> 
> ```
> 
> git pull
> 
> git checkout 97b4c1da03faf9bc35f348802fb7927231657e75
> 
> nix-shell
> 
> ```
> 
> 
> 
> 

On the release it is updated to use `next-node`, for stability I apply the hash tag here.

**Comment by aleeusgr** [comment]
got it running.

Post request returns:

<html><head><title>404 - Not Found</title></head><body><h1>404 - Not Found</h1><a href='https://www.spock.li'>powered by Spock</a></body>
