### ISSUE TITLE
How it works?

### ISSUE THREAD

**Issue by aleeusgr** [SIDANWhatever/plutus-cborhex-automation#32]
commit b038f8d39b505a61309bffaae832360556346139
| | Author: SIDANWhatever <wongkahinhinson@gmail.com>
| | Date:   Sat Nov 12 19:46:36 2022 +0800
| | 
| |     fix: changing the plutus-apps tag to next-node 
@SIDANWhatever 
~~please explain `next-node`, 🙇~~
>This checkout tag is corresponding to `next-node` tag of `plutus-apps`.

**Comment by aleeusgr** [comment]
commit a32635239f1239e6d976d5cb03bc74726d73ff70
|\  Merge: 86267cd e6d658e
| | Author: [SIDAN] Whatever <90688504+SIDANWhatever@users.noreply.github.com>
| | Date:   Wed Nov 16 09:46:54 2022 +0800
| | 
| |     Merge pull request #24 from SIDANWhatever/feature/terraform-vm
| |     
| |     Feature/terraform vm

**Comment by aleeusgr** [comment]
commit a32635239f1239e6d976d5cb03bc74726d73ff70
|\  Merge: 86267cd e6d658e
| | Author: [SIDAN] Whatever <90688504+SIDANWhatever@users.noreply.github.com>
| | Date:   Wed Nov 16 09:46:54 2022 +0800
| | 
| |     Merge pull request #24 from SIDANWhatever/feature/terraform-vm
| |     
| |     Feature/terraform vm

**Comment by HinsonSIDAN** [comment]
> commit b038f8d39b505a61309bffaae832360556346139
> 
> | | Author: SIDANWhatever <wongkahinhinson@gmail.com>
> 
> | | Date:   Sat Nov 12 19:46:36 2022 +0800
> 
> | | 
> 
> | |     fix: changing the plutus-apps tag to next-node 
> 
> @SIDANWhatever 
> 
> please explain `next-node`, 🙇
> 
> 

Basically I was just finding one tag which is compatible with PlutusV2. First I notice the v1.0.0-alpha1 tag, but after interacting with other Plutus dev, the current next-node tag is more stable.

next-node tag is the candidate for next release, so it should be the most up to date relatively (but not absolutely) stable tag.

**Comment by aleeusgr** [comment]
I have to look this through:
https://github.com/SIDANWhatever/plutus-cborhex-automation/commit/0cab0e61e235b168209e558aa950f652ce1f7cc0#diff-f1cfb684eb11e72cfaebe8d950b843001a7e70f37b10a1373a56bd764ed9a869

**Comment by HinsonSIDAN** [comment]
Closing as completed
