### ISSUE TITLE
How to supply your code?

### ISSUE THREAD

**Issue by aleeusgr** [SIDANWhatever/plutus-cborhex-automation#33]
1. Add your validator to example/src
2. Specify what you need here:

https://github.com/SIDANWhatever/plutus-cborhex-automation/blob/89ea6b7808849f92113b551a9bed9d7bd5763943/example/src/ParamScriptAPI.hs#L6

https://github.com/SIDANWhatever/plutus-cborhex-automation/blob/89ea6b7808849f92113b551a9bed9d7bd5763943/example/src/ParamScriptAPI.hs#L13

**Comment by aleeusgr** [comment]
https://github.com/SIDANWhatever/plutus-cborhex-automation/blob/main/example/src/TestingValidator.hs

**Comment by aleeusgr** [comment]
https://github.com/SIDANWhatever/plutus-cborhex-automation/blob/main/example/src/ParamScriptAPI.hs

**Comment by aleeusgr** [comment]
[Faucet](https://gitlab.com/gimbalabs/plutus-pbl-summer-2022/ppbl-course-02/-/blob/master/project-301-faucet/src/FaucetValidatorScript.hs)
<details>
  <summary> Ambiguous occurrence ‘withdrawalAmount’ </summary>

https://github.com/aleeusgr/plutus-cborhex-automation/issues/5
</details>

<details>
<summary>Type error </summary>
https://github.com/aleeusgr/plutus-cborhex-automation/issues/6
</details>

**Comment by aleeusgr** [comment]
OK, so the `plutus-apps` tag is different.
I can't test faucet with `next-node` cos I don't have working node at the moment.. 
Testing with recommended tag for the Faucet.

**Comment by aleeusgr** [comment]
[GPTE](https://gitlab.com/gimbalabs/plutus-pbl-summer-2022/projects/gpte/gpte-plutus-v2)

EscrowValidator, TreasuryValidator, ApprovalMinter, Types.

Changes in the code are needed, `import Types`

**Comment by HinsonSIDAN** [comment]
Please refer to the actual implementation for this issue.
